# Generated by Django 2.0.5 on 2018-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconnection',
            name='refresh_token',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='access_token',
            field=models.CharField(max_length=500),
        ),
    ]
