# Generated by Django 2.0.5 on 2018-05-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qbconnect', '0002_auto_20180531_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconnection',
            name='access_token_secret',
        ),
    ]
