# Generated by Django 2.0.5 on 2018-06-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qbconnect', '0003_remove_userconnection_access_token_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='access_token',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='company_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userconnection',
            name='refresh_token',
            field=models.TextField(null=True),
        ),
    ]
