# Generated by Django 2.0.5 on 2018-05-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='status',
            field=models.CharField(choices=[('Received', 'R'), ('InProgress', 'Q'), ('Completed', 'C'), ('Failed', 'F')], max_length=50, null=True),
        ),
    ]
