# Generated by Django 2.0.5 on 2018-06-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_auto_20180605_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFileResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.IntegerField(max_length=100)),
                ('status', models.CharField(choices=[('Success', 'S'), ('Failed', 'F'), ('Warning', 'W')], default='S', max_length=50)),
                ('error_message', models.TextField(null=True)),
                ('error_response', models.TextField(null=True)),
                ('csv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.CsvFile')),
            ],
        ),
    ]
