# Generated by Django 2.0.5 on 2018-06-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_csvfileresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileresults',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
