# Generated by Django 2.0.5 on 2018-06-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_auto_20180605_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='status',
            field=models.CharField(choices=[('R', 'Received'), ('Q', 'InProgress'), ('C', 'Completed'), ('F', 'Failed')], default='R', max_length=50),
        ),
    ]
