# Generated by Django 2.0.5 on 2018-06-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_auto_20180606_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileresults',
            name='customer_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='csvfileresults',
            name='invoice_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
