# Generated by Django 2.0.5 on 2018-06-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20180610_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfileresults',
            name='customer_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
