# Generated by Django 2.0.5 on 2018-07-12 20:16

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0013_auto_20180712_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=invoice.models.CsvFile.uid_upload_to),
        ),
    ]
