# Generated by Django 2.0.5 on 2018-07-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0014_auto_20180712_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='batch_type',
            field=models.CharField(default='CSV', max_length=50),
        ),
    ]
