# Generated by Django 2.0.5 on 2018-07-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_csvfileresults_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfileresults',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
